### ISSUE TITLE
Songs are not downloading as expected 

### ISSUE THREAD

**Issue by sanalsunny** [Footsiefat/zspotify#177] opened 2021-11-01 19:10 UTC
Songs are not fully downloaded. see the screenshot 

![image](https://user-images.githubusercontent.com/83308684/139727536-8a781525-72b4-4f4c-8c60-a4ea92f87e23.png)

so here most of the songs stoped processing midway

**Comment by JamesKai** [comment] 2021-11-02 00:19
This is the exact same issue as #162

**Comment by logykk** [comment] 2021-11-02 08:03
Duplicate of #162, move discussion over there.

**Closed by logykk** 2021-11-02 08:03 UTC
