### ISSUE TITLE
Songs only partially downloading

### ISSUE THREAD

**Issue by SlimeyIceCream** [Footsiefat/zspotify#162] opened 2021-10-28 00:07 UTC
When i download songs from a playlist, many of them are only partially downloaded, for instance sometimes the application will only download the first 20 seconds, and then move on to the next item in the playlist.

**Comment by cooper7692** [comment] 2021-10-31 04:25
> When i download songs from a playlist, many of them are only partially downloaded, for instance sometimes the application will only download the first 20 seconds, and then move on to the next item in the playlist.
we might have found the cause of this problem, a proper fix will follow as soon as possible. but there are a lot of balls in the air atm for the developers.

**Comment by dig65** [comment] 2021-10-31 11:11
This issue occurs with "album" downloads as well. Right now, using the latest build of the script (as of 10/31/2021) I am experiencing at least one partial/failed track download on each album, often more.

I can add these observations:
- when I delete what I know to be partial tracks, and redo the album download (with "skip existing" set in the config), the first missing track is properly downloaded, but each subsequent missing track will result in a partial download. Deleting them, and redoing again will exhibit the same behavior, i.e., the first missing track is properly downloaded and each subsequent is a partial.
- There was some discussion in Discord of this being related to the focus of the app window. I have found that in all cases, keeping the app window in focus does NOT prevent the problem. It occurs even when the app is constantly in focus.

**Comment by yiannisha** [comment] 2021-10-31 17:25
I am currently working on implementing some code that will compare the duration of the original song vs the length of the file downloaded. We'll need some more time to decide what we're gonna do after that though.

**Comment by yiannisha** [comment] 2021-11-02 06:06
So I've found a way to maybe temporarily fix this. It just tries 10 times to get more data if it gets none and that seems to work. Just made PR#178 . I'll tell the guys over in our discord to test it out.

**Comment by logykk** [comment] 2021-11-08 00:12
Is this still happening to anyone? Closing this otherwise

**Comment by MaKraMc** [comment] 2021-11-11 18:58
Still happens to me on version 2.4.1 (Windows)

**Comment by logykk** [comment] 2021-11-11 20:43
@MaKraMc is that using the executable or the source?

**Comment by MaKraMc** [comment] 2021-11-12 13:39
I am using the executable. Today it happend with the same songs. I also tried downloading as mp3, same problem.

**Comment by MaKraMc** [comment] 2021-11-12 13:43
Tried it with PowerShell and CMD. Both admin and not admin. Same songs, same Problem.

**Comment by logykk** [comment] 2021-11-13 05:37
As of right now all of the executable releases have the bug. You'll need to either run the source code or wait for a new release.

**Comment by MaKraMc** [comment] 2021-11-14 13:38
Okay, thanks for the info. I tried it on Linux and it worked out of the box perfectly fine!

**Comment by logykk** [comment] 2021-11-21 08:25
Haven't heard anyone mention this bug in a while. I think that little 2 line fix worked. Someone reopen this if it's still broken.

**Closed by logykk** 2021-11-21 08:25 UTC
